### ISSUE TITLE
check-emergency-rooms-quebec failed test

### ISSUE THREAD

**Issue by gst** [savoirfairelinux/monitoring-tools#35]
https://travis-ci.org/savoirfairelinux/monitoring-tools/builds/56729697

to be investigated..

```
======================================================================
FAIL: test_critical_output (test_check_emergency_rooms_quebec.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/savoirfairelinux/monitoring-tools/plugins/check-emergency-rooms-quebec/tests/test_check_emergency_rooms_quebec.py", line 55, in test_critical_output
    self.execute(Plugin, args, 2, 'CRITICAL - [0-9]*%')
  File "/home/travis/build/savoirfairelinux/monitoring-tools/plugins/check-emergency-rooms-quebec/env/local/lib/python2.7/site-packages/shinkenplugins/test.py", line 68, in execute
    self.assertRegexpMatches(stdout_output, stdout_pattern)
AssertionError: Regexp didn't match: 'CRITICAL - [0-9]*%' not found in u'CRITICAL: 128%|functional_stretchers=585;;;0; occupied_stretchers=752;;;0; occupation=128;-1.0;-1.0;0;100'
======================================================================
FAIL: test_no_args (test_check_emergency_rooms_quebec.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/savoirfairelinux/monitoring-tools/plugins/check-emergency-rooms-quebec/tests/test_check_emergency_rooms_quebec.py", line 47, in test_no_args
    self.execute(Plugin, [], 3, 'Arguments error: argument url is mandatory')
  File "/home/travis/build/savoirfairelinux/monitoring-tools/plugins/check-emergency-rooms-quebec/env/local/lib/python2.7/site-packages/shinkenplugins/test.py", line 68, in execute
    self.assertRegexpMatches(stdout_output, stdout_pattern)
AssertionError: Regexp didn't match: 'Arguments error: argument url is mandatory' not found in ''
```

**Comment by gst** [comment]
Will be fixed when https://github.com/savoirfairelinux/monitoring-tools/pull/36 is merged.
